//! GeoLibre tool: piecewise rubbersheet conflation transform.
//!
//! Pure-Rust counterpart of ArcGIS Pro's *Rubbersheet Features* +
//! *Generate Rubbersheet Links* (Editing). `detect_feature_changes` (#96)
//! shipped the feature matcher this was designed to feed; nothing bundled
//! performs the conflation *transform*. Rubbersheeting aligns one dataset onto
//! another (OSM ↔ authoritative, versioned data) by warping space so control
//! points ("links") land on their targets and everything between deforms
//! smoothly.
//!
//! Displacement links are either supplied as a `--links` line layer (each line's
//! first vertex is the *from* point, last vertex the *to* point) or generated
//! from a `--target` layer by matching each input feature's representative point
//! to the nearest target point within `--search_distance`.
//!
//! The warp:
//!
//! * **linear** (default) — a Delaunay triangulation of the *from* points
//!   (self-contained Bowyer–Watson); inside a triangle the displacement is the
//!   barycentric blend of its three corners' displacements (exact at the links,
//!   piecewise-affine between). Outside the hull it falls back to inverse-
//!   distance weighting of all links.
//! * **idw** — inverse-distance-weighted displacement everywhere.
//!
//! Every vertex of every input geometry is displaced; distances are in the layer
//! CRS units. Reports the link count and the mean applied displacement.

use std::collections::BTreeMap;

use serde_json::{json, Value};
use wbcore::{
    LicenseTier, Tool, ToolArgs, ToolCategory, ToolContext, ToolError, ToolMetadata, ToolParamSpec,
    ToolRunResult,
};
use wbvector::{Coord, Geometry, Ring};

use crate::vector_common::{load_input_layer, parse_optional_str, write_or_store_layer};

pub struct RubbersheetFeaturesTool;

impl Tool for RubbersheetFeaturesTool {
    fn metadata(&self) -> ToolMetadata {
        ToolMetadata {
            id: "rubbersheet_features",
            display_name: "Rubbersheet Features",
            summary: "Warp a vector layer to align with a target using displacement links: a Delaunay-TIN piecewise-affine (or IDW) transform that lands control points on their targets and deforms everything between smoothly — the conflation transform, like ArcGIS Rubbersheet Features.",
            category: ToolCategory::Vector,
            license_tier: LicenseTier::Open,
            params: vec![
                ToolParamSpec {
                    name: "input",
                    description: "Input vector layer to adjust (any geometry type).",
                    required: true,
                },
                ToolParamSpec {
                    name: "output",
                    description: "Optional output vector path (driver from extension). If omitted, stored in memory.",
                    required: false,
                },
                ToolParamSpec {
                    name: "links",
                    description: "Optional line layer of displacement links (each line: first vertex = from, last vertex = to).",
                    required: false,
                },
                ToolParamSpec {
                    name: "target",
                    description: "Optional target vector layer; links are generated by matching each input feature's representative point to the nearest target within search_distance.",
                    required: false,
                },
                ToolParamSpec {
                    name: "search_distance",
                    description: "Max distance to match input to target when generating links (CRS units). Required with 'target'.",
                    required: false,
                },
                ToolParamSpec {
                    name: "method",
                    description: "'linear' (Delaunay TIN piecewise-affine, default) or 'idw' (inverse-distance-weighted).",
                    required: false,
                },
                ToolParamSpec {
                    name: "power",
                    description: "IDW power for the falloff outside the TIN / for method=idw. Default 2.",
                    required: false,
                },
            ],
        }
    }

    fn validate(&self, args: &ToolArgs) -> Result<(), ToolError> {
        require_str(args, "input")?;
        parse_params(args)?;
        Ok(())
    }

    fn run(&self, args: &ToolArgs, ctx: &ToolContext) -> Result<ToolRunResult, ToolError> {
        let input = require_str(args, "input")?;
        let output = parse_optional_str(args, "output")?;
        let prm = parse_params(args)?;

        let mut layer = load_input_layer(input)?;

        // ── Obtain displacement links ─────────────────────────────────────────
        let links = match (&prm.links, &prm.target) {
            (Some(links_path), _) => {
                let ll = load_input_layer(links_path)?;
                links_from_layer(&ll)
            }
            (None, Some(target_path)) => {
                let search = prm.search_distance.ok_or_else(|| {
                    ToolError::Validation("'target' requires 'search_distance'".to_string())
                })?;
                let target = load_input_layer(target_path)?;
                links_from_matching(&layer, &target, search)
            }
            (None, None) => {
                return Err(ToolError::Validation(
                    "provide either 'links' (a link layer) or 'target' + 'search_distance'"
                        .to_string(),
                ))
            }
        };
        if links.is_empty() {
            return Err(ToolError::Execution(
                "no displacement links (nothing to align to)".to_string(),
            ));
        }

        ctx.progress.info(&format!(
            "{} link(s); building {} warp",
            links.len(),
            match prm.method {
                Method::Linear => "TIN",
                Method::Idw => "IDW",
            }
        ));

        // ── Build the warp ────────────────────────────────────────────────────
        let warp = Warp::build(&links, prm.method, prm.power);

        // ── Apply to every vertex; track mean displacement ────────────────────
        let mut total_disp = 0.0;
        let mut n_vert = 0usize;
        for feature in layer.features.iter_mut() {
            if let Some(g) = feature.geometry.as_ref() {
                let new = map_geometry(g, &mut |x, y| {
                    let (dx, dy) = warp.displacement(x, y);
                    total_disp += (dx * dx + dy * dy).sqrt();
                    n_vert += 1;
                    (x + dx, y + dy)
                });
                feature.geometry = Some(new);
            }
        }
        layer.extent = None;

        let mean_disp = if n_vert > 0 {
            total_disp / n_vert as f64
        } else {
            0.0
        };
        ctx.progress.info(&format!(
            "warped {n_vert} vertex(es); mean displacement {mean_disp:.4}"
        ));

        let feature_count = layer.len();
        let out_path = write_or_store_layer(layer, output)?;

        let mut outputs = BTreeMap::new();
        outputs.insert("output".to_string(), json!(out_path));
        outputs.insert("feature_count".to_string(), json!(feature_count));
        outputs.insert("link_count".to_string(), json!(links.len()));
        outputs.insert("vertices_warped".to_string(), json!(n_vert));
        outputs.insert("mean_displacement".to_string(), json!(mean_disp));
        Ok(ToolRunResult { outputs })
    }
}

// ── Links ────────────────────────────────────────────────────────────────────

/// A displacement link: a `from` control point and its displacement vector.
#[derive(Clone, Copy)]
struct Link {
    fx: f64,
    fy: f64,
    dx: f64,
    dy: f64,
}

fn links_from_layer(layer: &wbvector::Layer) -> Vec<Link> {
    let mut out = Vec::new();
    for feature in layer.features.iter() {
        if let Some(Geometry::LineString(cs)) = feature.geometry.as_ref() {
            if cs.len() >= 2 {
                let a = &cs[0];
                let b = &cs[cs.len() - 1];
                out.push(Link {
                    fx: a.x,
                    fy: a.y,
                    dx: b.x - a.x,
                    dy: b.y - a.y,
                });
            }
        } else if let Some(Geometry::MultiLineString(lines)) = feature.geometry.as_ref() {
            for cs in lines {
                if cs.len() >= 2 {
                    let a = &cs[0];
                    let b = &cs[cs.len() - 1];
                    out.push(Link {
                        fx: a.x,
                        fy: a.y,
                        dx: b.x - a.x,
                        dy: b.y - a.y,
                    });
                }
            }
        }
    }
    out
}

fn links_from_matching(
    input: &wbvector::Layer,
    target: &wbvector::Layer,
    search: f64,
) -> Vec<Link> {
    let tpts: Vec<(f64, f64)> = target
        .features
        .iter()
        .filter_map(|f| f.geometry.as_ref().and_then(representative_xy))
        .collect();
    let mut out = Vec::new();
    for f in input.features.iter() {
        let Some((x, y)) = f.geometry.as_ref().and_then(representative_xy) else {
            continue;
        };
        let mut best: Option<(f64, (f64, f64))> = None;
        for &t in &tpts {
            let d = (x - t.0).hypot(y - t.1);
            if d <= search && best.is_none_or(|(bd, _)| d < bd) {
                best = Some((d, t));
            }
        }
        if let Some((_, t)) = best {
            out.push(Link {
                fx: x,
                fy: y,
                dx: t.0 - x,
                dy: t.1 - y,
            });
        }
    }
    out
}

// ── Warp (TIN + IDW) ─────────────────────────────────────────────────────────

#[derive(Clone, Copy, PartialEq, Eq)]
enum Method {
    Linear,
    Idw,
}

struct Warp<'a> {
    links: &'a [Link],
    method: Method,
    power: f64,
    tris: Vec<[usize; 3]>,
}

impl<'a> Warp<'a> {
    fn build(links: &'a [Link], method: Method, power: f64) -> Self {
        let tris = if method == Method::Linear && links.len() >= 3 {
            let pts: Vec<(f64, f64)> = links.iter().map(|l| (l.fx, l.fy)).collect();
            delaunay(&pts)
        } else {
            Vec::new()
        };
        Warp {
            links,
            method,
            power,
            tris,
        }
    }

    /// Displacement (dx, dy) to apply at world (x, y).
    fn displacement(&self, x: f64, y: f64) -> (f64, f64) {
        if self.method == Method::Linear && !self.tris.is_empty() {
            for &[a, b, c] in &self.tris {
                let (la, lb, lc) = (self.links[a], self.links[b], self.links[c]);
                if let Some((wa, wb, wc)) =
                    barycentric(x, y, (la.fx, la.fy), (lb.fx, lb.fy), (lc.fx, lc.fy))
                {
                    return (
                        wa * la.dx + wb * lb.dx + wc * lc.dx,
                        wa * la.dy + wb * lb.dy + wc * lc.dy,
                    );
                }
            }
            // Outside the hull: fall through to IDW.
        }
        self.idw(x, y)
    }

    fn idw(&self, x: f64, y: f64) -> (f64, f64) {
        let mut sx = 0.0;
        let mut sy = 0.0;
        let mut sw = 0.0;
        for l in self.links {
            let d = (x - l.fx).hypot(y - l.fy);
            if d < 1e-9 {
                return (l.dx, l.dy);
            }
            let w = 1.0 / d.powf(self.power);
            sx += w * l.dx;
            sy += w * l.dy;
            sw += w;
        }
        if sw > 0.0 {
            (sx / sw, sy / sw)
        } else {
            (0.0, 0.0)
        }
    }
}

/// Barycentric weights of (px,py) in triangle a,b,c, or `None` if outside.
fn barycentric(
    px: f64,
    py: f64,
    a: (f64, f64),
    b: (f64, f64),
    c: (f64, f64),
) -> Option<(f64, f64, f64)> {
    let det = (b.1 - c.1) * (a.0 - c.0) + (c.0 - b.0) * (a.1 - c.1);
    if det.abs() < 1e-18 {
        return None;
    }
    let wa = ((b.1 - c.1) * (px - c.0) + (c.0 - b.0) * (py - c.1)) / det;
    let wb = ((c.1 - a.1) * (px - c.0) + (a.0 - c.0) * (py - c.1)) / det;
    let wc = 1.0 - wa - wb;
    let eps = -1e-9;
    (wa >= eps && wb >= eps && wc >= eps).then_some((wa, wb, wc))
}

/// Bowyer–Watson Delaunay triangulation; returns triangles as index triples into
/// `pts` (super-triangle triangles removed).
fn delaunay(pts: &[(f64, f64)]) -> Vec<[usize; 3]> {
    let n = pts.len();
    if n < 3 {
        return Vec::new();
    }
    // Super-triangle enclosing all points.
    let (mut minx, mut miny, mut maxx, mut maxy) = (f64::MAX, f64::MAX, f64::MIN, f64::MIN);
    for &(x, y) in pts {
        minx = minx.min(x);
        miny = miny.min(y);
        maxx = maxx.max(x);
        maxy = maxy.max(y);
    }
    let dmax = (maxx - minx).max(maxy - miny).max(1.0) * 20.0;
    let (mx, my) = ((minx + maxx) / 2.0, (miny + maxy) / 2.0);
    let mut verts: Vec<(f64, f64)> = pts.to_vec();
    let s0 = verts.len();
    verts.push((mx - dmax, my - dmax));
    verts.push((mx + dmax, my - dmax));
    verts.push((mx, my + dmax));
    let mut tris: Vec<[usize; 3]> = vec![[s0, s0 + 1, s0 + 2]];

    for i in 0..n {
        let p = verts[i];
        // Triangles whose circumcircle contains p are "bad".
        let mut bad: Vec<usize> = Vec::new();
        for (ti, t) in tris.iter().enumerate() {
            if in_circumcircle(p, verts[t[0]], verts[t[1]], verts[t[2]]) {
                bad.push(ti);
            }
        }
        // Boundary of the polygonal hole = edges on exactly one bad triangle.
        let mut boundary: Vec<(usize, usize)> = Vec::new();
        for &ti in &bad {
            let t = tris[ti];
            for e in [(t[0], t[1]), (t[1], t[2]), (t[2], t[0])] {
                let shared = bad.iter().any(|&oj| {
                    oj != ti && {
                        let o = tris[oj];
                        let edges = [(o[0], o[1]), (o[1], o[2]), (o[2], o[0])];
                        edges
                            .iter()
                            .any(|&(u, v)| (u == e.0 && v == e.1) || (u == e.1 && v == e.0))
                    }
                });
                if !shared {
                    boundary.push(e);
                }
            }
        }
        // Remove bad triangles (descending index) and add new ones to p.
        bad.sort_unstable_by(|a, b| b.cmp(a));
        for &ti in &bad {
            tris.swap_remove(ti);
        }
        for (u, v) in boundary {
            tris.push([u, v, i]);
        }
    }
    // Drop any triangle touching a super vertex.
    tris.retain(|t| t.iter().all(|&v| v < s0));
    tris
}

fn in_circumcircle(p: (f64, f64), a: (f64, f64), b: (f64, f64), c: (f64, f64)) -> bool {
    let ax = a.0 - p.0;
    let ay = a.1 - p.1;
    let bx = b.0 - p.0;
    let by = b.1 - p.1;
    let cx = c.0 - p.0;
    let cy = c.1 - p.1;
    let det = (ax * ax + ay * ay) * (bx * cy - cx * by) - (bx * bx + by * by) * (ax * cy - cx * ay)
        + (cx * cx + cy * cy) * (ax * by - bx * ay);
    // Orientation-aware: sign of the triangle area flips the test.
    let area2 = (b.0 - a.0) * (c.1 - a.1) - (c.0 - a.0) * (b.1 - a.1);
    if area2 > 0.0 {
        det > 0.0
    } else {
        det < 0.0
    }
}

// ── Geometry mapping ─────────────────────────────────────────────────────────

fn map_geometry(geom: &Geometry, f: &mut impl FnMut(f64, f64) -> (f64, f64)) -> Geometry {
    let map_chain = |cs: &[Coord], f: &mut dyn FnMut(f64, f64) -> (f64, f64)| -> Vec<Coord> {
        cs.iter()
            .map(|c| {
                let (x, y) = f(c.x, c.y);
                Coord::xy(x, y)
            })
            .collect()
    };
    match geom {
        Geometry::Point(c) => {
            let (x, y) = f(c.x, c.y);
            Geometry::Point(Coord::xy(x, y))
        }
        Geometry::MultiPoint(cs) => Geometry::MultiPoint(map_chain(cs, f)),
        Geometry::LineString(cs) => Geometry::LineString(map_chain(cs, f)),
        Geometry::MultiLineString(lines) => {
            Geometry::MultiLineString(lines.iter().map(|l| map_chain(l, f)).collect())
        }
        Geometry::Polygon {
            exterior,
            interiors,
        } => Geometry::Polygon {
            exterior: Ring::new(map_chain(exterior.coords(), f)),
            interiors: interiors
                .iter()
                .map(|r| Ring::new(map_chain(r.coords(), f)))
                .collect(),
        },
        Geometry::MultiPolygon(parts) => Geometry::MultiPolygon(
            parts
                .iter()
                .map(|(e, holes)| {
                    (
                        Ring::new(map_chain(e.coords(), f)),
                        holes
                            .iter()
                            .map(|r| Ring::new(map_chain(r.coords(), f)))
                            .collect(),
                    )
                })
                .collect(),
        ),
        Geometry::GeometryCollection(gs) => {
            Geometry::GeometryCollection(gs.iter().map(|g| map_geometry(g, f)).collect())
        }
    }
}

fn representative_xy(geom: &Geometry) -> Option<(f64, f64)> {
    let mut sx = 0.0;
    let mut sy = 0.0;
    let mut n = 0u64;
    let mut add = |c: &Coord| {
        sx += c.x;
        sy += c.y;
        n += 1;
    };
    fn walk(g: &Geometry, add: &mut impl FnMut(&Coord)) {
        match g {
            Geometry::Point(c) => add(c),
            Geometry::LineString(cs) | Geometry::MultiPoint(cs) => cs.iter().for_each(add),
            Geometry::MultiLineString(ls) => ls.iter().flatten().for_each(add),
            Geometry::Polygon {
                exterior,
                interiors,
            } => {
                exterior.coords().iter().for_each(&mut *add);
                interiors
                    .iter()
                    .for_each(|r| r.coords().iter().for_each(&mut *add));
            }
            Geometry::MultiPolygon(ps) => {
                for (e, h) in ps {
                    e.coords().iter().for_each(&mut *add);
                    h.iter().for_each(|r| r.coords().iter().for_each(&mut *add));
                }
            }
            Geometry::GeometryCollection(gs) => gs.iter().for_each(|g| walk(g, add)),
        }
    }
    walk(geom, &mut add);
    (n > 0).then(|| (sx / n as f64, sy / n as f64))
}

// ── Parameters ────────────────────────────────────────────────────────────────

struct Params {
    links: Option<String>,
    target: Option<String>,
    search_distance: Option<f64>,
    method: Method,
    power: f64,
}

fn parse_params(args: &ToolArgs) -> Result<Params, ToolError> {
    let links = parse_optional_str(args, "links")?.map(str::to_string);
    let target = parse_optional_str(args, "target")?.map(str::to_string);
    let search_distance = parse_optional_f64(args, "search_distance")?;
    let method = match parse_optional_str(args, "method")? {
        None => Method::Linear,
        Some(s) => match s.trim().to_ascii_lowercase().as_str() {
            "linear" | "tin" => Method::Linear,
            "idw" => Method::Idw,
            other => {
                return Err(ToolError::Validation(format!(
                    "'method' must be 'linear' or 'idw', got '{other}'"
                )))
            }
        },
    };
    let power = parse_optional_f64(args, "power")?.unwrap_or(2.0);
    if !(power > 0.0 && power.is_finite()) {
        return Err(ToolError::Validation(
            "'power' must be a positive number".to_string(),
        ));
    }
    Ok(Params {
        links,
        target,
        search_distance,
        method,
        power,
    })
}

fn require_str<'a>(args: &'a ToolArgs, key: &str) -> Result<&'a str, ToolError> {
    args.get(key)
        .and_then(Value::as_str)
        .map(str::trim)
        .filter(|s| !s.is_empty())
        .ok_or_else(|| ToolError::Validation(format!("missing required string parameter '{key}'")))
}

fn parse_optional_f64(args: &ToolArgs, key: &str) -> Result<Option<f64>, ToolError> {
    match args.get(key) {
        None | Some(Value::Null) => Ok(None),
        Some(Value::Number(n)) => Ok(n.as_f64()),
        Some(Value::String(s)) if s.trim().is_empty() => Ok(None),
        Some(Value::String(s)) => s
            .trim()
            .parse::<f64>()
            .map(Some)
            .map_err(|_| ToolError::Validation(format!("parameter '{key}' must be a number"))),
        Some(_) => Err(ToolError::Validation(format!(
            "parameter '{key}' must be a number"
        ))),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use wbcore::{AllowAllCapabilities, ProgressSink};
    use wbvector::{memory_store, GeometryType, Layer};

    struct NullProgress;
    impl ProgressSink for NullProgress {}

    fn ctx() -> ToolContext<'static> {
        ToolContext {
            progress: &NullProgress,
            capabilities: &AllowAllCapabilities,
        }
    }

    fn point_layer(pts: &[(f64, f64)]) -> String {
        let mut l = Layer::new("p")
            .with_geom_type(GeometryType::Point)
            .with_crs_epsg(3857);
        for &(x, y) in pts {
            l.add_feature(Some(Geometry::point(x, y)), &[]).unwrap();
        }
        let id = memory_store::put_vector(l);
        memory_store::make_vector_memory_path(&id)
    }

    type LinkPair = ((f64, f64), (f64, f64));

    fn link_layer(links: &[LinkPair]) -> String {
        let mut l = Layer::new("links")
            .with_geom_type(GeometryType::LineString)
            .with_crs_epsg(3857);
        for &(a, b) in links {
            l.add_feature(
                Some(Geometry::line_string(vec![
                    Coord::xy(a.0, a.1),
                    Coord::xy(b.0, b.1),
                ])),
                &[],
            )
            .unwrap();
        }
        let id = memory_store::put_vector(l);
        memory_store::make_vector_memory_path(&id)
    }

    fn run(args: serde_json::Value) -> (ToolRunResult, Layer) {
        let args: ToolArgs = serde_json::from_value(args).unwrap();
        let out = RubbersheetFeaturesTool.run(&args, &ctx()).unwrap();
        let layer = load_input_layer(out.outputs["output"].as_str().unwrap()).unwrap();
        (out, layer)
    }

    fn pt(layer: &Layer, i: usize) -> (f64, f64) {
        match layer.features[i].geometry.as_ref().unwrap() {
            Geometry::Point(c) => (c.x, c.y),
            other => panic!("expected point, got {other:?}"),
        }
    }

    /// A uniform translation link field shifts everything by the same vector.
    #[test]
    fn uniform_translation() {
        // Four corner links all displacing by (+10, +5).
        let links = link_layer(&[
            ((0.0, 0.0), (10.0, 5.0)),
            ((100.0, 0.0), (110.0, 5.0)),
            ((100.0, 100.0), (110.0, 105.0)),
            ((0.0, 100.0), (10.0, 105.0)),
        ]);
        let input = point_layer(&[(50.0, 50.0), (25.0, 75.0)]);
        let (_o, layer) = run(json!({ "input": input, "links": links, "method": "linear" }));
        let (x, y) = pt(&layer, 0);
        assert!(
            (x - 60.0).abs() < 1e-6 && (y - 55.0).abs() < 1e-6,
            "point 0 -> ({x},{y}), want (60,55)"
        );
        let (x1, y1) = pt(&layer, 1);
        assert!((x1 - 35.0).abs() < 1e-6 && (y1 - 80.0).abs() < 1e-6);
    }

    /// A control point lands exactly on its target (barycentric exactness).
    #[test]
    fn control_points_hit_targets() {
        let links = [
            ((0.0, 0.0), (0.0, 0.0)),
            ((100.0, 0.0), (100.0, 0.0)),
            ((50.0, 100.0), (50.0, 130.0)), // this one moves up 30
            ((50.0, 40.0), (50.0, 40.0)),
        ];
        let ll = link_layer(&links);
        // Input includes the moving control point itself.
        let input = point_layer(&[(50.0, 100.0)]);
        let (_o, layer) = run(json!({ "input": input, "links": ll, "method": "linear" }));
        let (x, y) = pt(&layer, 0);
        assert!(
            (x - 50.0).abs() < 1e-6 && (y - 130.0).abs() < 1e-6,
            "control pt not on target: ({x},{y})"
        );
    }

    /// IDW mode with two links interpolates displacement by distance.
    #[test]
    fn idw_mode_interpolates() {
        let links = link_layer(&[((0.0, 0.0), (0.0, 10.0)), ((100.0, 0.0), (100.0, 0.0))]);
        // Midpoint should get ~half the first link's +10 in y (equal weights).
        let input = point_layer(&[(50.0, 0.0)]);
        let (_o, layer) =
            run(json!({ "input": input, "links": links, "method": "idw", "power": 2.0 }));
        let (_x, y) = pt(&layer, 0);
        assert!((y - 5.0).abs() < 1e-6, "idw midpoint y = {y}, want 5");
    }

    /// target mode generates links by nearest matching.
    #[test]
    fn target_mode_generates_links() {
        let input = point_layer(&[(0.0, 0.0), (100.0, 0.0), (50.0, 80.0)]);
        let target = point_layer(&[(2.0, 1.0), (101.0, -1.0), (52.0, 82.0)]);
        let (out, _l) = run(json!({
            "input": input, "target": target, "search_distance": 10.0, "method": "idw",
        }));
        assert_eq!(out.outputs["link_count"], json!(3));
    }

    #[test]
    fn rejects_bad_params() {
        let bad = |v: serde_json::Value| {
            let args: ToolArgs = serde_json::from_value(v).unwrap();
            RubbersheetFeaturesTool.validate(&args)
        };
        assert!(bad(json!({})).is_err());
        assert!(bad(json!({ "input": "a.geojson", "method": "spline" })).is_err());
        assert!(bad(json!({ "input": "a.geojson", "links": "l.geojson" })).is_ok());
    }
}
